import { randomUUID, createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { Pool } from 'pg';
import { beforeAll, afterAll, it, expect } from 'vitest';
import { createProjectUnitOfWork, isDatabaseReady } from '@property/database';
import { migrate } from '@property/database/migrate';
import { ProjectService } from '@property/services';
import { rectangleFacts } from './site-fixtures';

const connectionString=process.env.TEST_DATABASE_URL;
if(!connectionString || !new URL(connectionString).pathname.endsWith('_test')) throw new Error('An isolated TEST_DATABASE_URL ending in _test is required.');
const schema=`test_upgrade_${randomUUID().replaceAll('-','')}`;
const admin=new Pool({connectionString});
const pool=new Pool({connectionString,options:`-c search_path=${schema},public`});
beforeAll(async()=>{await admin.query(`CREATE SCHEMA ${schema}`);});
afterAll(async()=>{await pool.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
it('upgrades an applied, populated Phase 1 database without rewriting any historical snapshot or audit',async()=>{
  const sql=await readFile(new URL('../packages/database/migrations/001_foundation.sql',import.meta.url),'utf8');
  await pool.query(sql);
  await pool.query('CREATE TABLE schema_migrations(name text PRIMARY KEY, checksum text NOT NULL, applied_at timestamptz NOT NULL DEFAULT now())');
  await pool.query('INSERT INTO schema_migrations(name,checksum) VALUES($1,$2)',['001_foundation.sql',createHash('sha256').update(sql).digest('hex')]);
  const owner={userId:randomUUID()};
  await pool.query('INSERT INTO "user"(id,name,email) VALUES($1,$2,$3)',[owner.userId,'Upgrade test',`${owner.userId}@example.test`]);
  const service=new ProjectService(createProjectUnitOfWork(pool),randomUUID,()=>new Date());
  const project=await service.create(owner,{name:'Pre-existing Phase 1 project'});
  await service.update(owner,project.id,{expectedRevision:1,name:'Existing project, renamed',changeReason:'Before schema evolution'});
  const versions=(await pool.query('SELECT row_to_json(v)::text AS value FROM project_versions v ORDER BY revision')).rows;
  const audit=(await pool.query('SELECT row_to_json(a)::text AS value FROM audit_events a ORDER BY occurred_at')).rows;
  expect(await isDatabaseReady(pool)).toBe(false);
  await migrate(pool);
  expect(await isDatabaseReady(pool)).toBe(true);
  expect((await pool.query('SELECT row_to_json(v)::text AS value FROM project_versions v ORDER BY revision')).rows).toEqual(versions);
  expect((await pool.query('SELECT row_to_json(a)::text AS value FROM audit_events a ORDER BY occurred_at')).rows).toEqual(audit);
  expect((await service.site(owner,project.id)).site).toBeNull();
  await service.saveSite(owner,project.id,{expectedRevision:2,changeReason:'First site entry after upgrade',site:rectangleFacts()});
  const history=(await service.versions(owner,project.id)).items;
  expect(history.map(v=>v.snapshot.schemaVersion)).toEqual([2,1,1]);
  expect(history[0]!.snapshot.site?.derived.calculatedArea?.value).toBe('200000000');
  await migrate(pool);
  expect((await pool.query('SELECT count(*)::int AS count FROM schema_migrations')).rows[0].count).toBe(3);
});
